#!/usr/bin/env bash
# Infinite loop displaying a message, prints "I am invincible!!!" when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
